name = "auth_ic0_app"
type = "webpack"
account_id = "64059940cc95339fc7e5888f431876ee"
workers_dev = false
route = "auth.ic0.app/*"
zone_id = "56caec9ad0f274cef8991c0995b9b465"
webpack_config = "webpack.config.js"

[site]
bucket = "./node_modules/@dfinity/identity-provider/dist"
entry-point = "./"
