name = "bootstrap_ic0_app"
type = "webpack"
account_id = "64059940cc95339fc7e5888f431876ee"
workers_dev = false
route = "ic0.app/*"
zone_id = "56caec9ad0f274cef8991c0995b9b465"
webpack_config = "webpack.config.js"
kv_namespaces = [
    { binding = "Config", id = "df1b0a7ec54d46b5b28f8a36fc8e2a22" }
]

[site]
bucket = "./node_modules/@dfinity/bootstrap/dist"
entry-point = "./"
