name: Prepare

description: Select Node.js version and install dependencies

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    type: string
  node-version-file:
    description: 'Path to the Node.js version file'
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci
