name: Test Docs Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main
        with:
          node_version_file: '.nvmrc'

      - name: Generate docs
        run: pnpm run -F docs build

  aggregate:
    name: docs:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check build docs result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
