name: Mitm

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ghc: ['8.8.4']
        spec:
          - '0.16.1'
        node:
          - 20

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g npm

      - run: npm install

      # build monorepo incl. each subpackage
      - run: npm run build --workspaces --if-present

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip3 install mitmproxy~=10.0.0

      - uses: dfinity/setup-dfx@main

      - name: running dfx
        id: dfx
        run: |
          dfx start --background

      - name: Running mitmdump
        id: mitmdump
        run: |
          set -ex
          mitmdump -p 8888 --mode reverse:https://icp-api.io \
            --modify-headers '/~s/Transfer-Encoding/' \
            --modify-body '/~s/Hello/Hullo' \
            &
          sleep 20

      - name: mitm e2e
        env:
          CI: true
        run: npm run mitm --workspaces --if-present

  aggregate:
    name: mitm:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
