name: Mitm

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        ghc: ['8.8.4']
        spec:
          - '0.16.1'
        node:
          - 16

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g npm

      - run: npm install

      # build monorepo incl. each subpackage
      - run: npm run build --workspaces --if-present

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip3 install mitmproxy~=8.0.0

      - run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"

      - name: running dfx
        id: dfx
        run: |
          dfx start --background

      - name: Running mitmdump
        id: mitmdump
        run: |
          set -ex
          mitmdump -p 8888 --mode reverse:http://127.0.0.1:8000 \
            --modify-headers '/~s/Transfer-Encoding/' \
            --modify-body '/~s/Hello/Hullo' \
            &
          sleep 5

      - name: mitm e2e
        env:
          CI: true
          REPLICA_PORT: 8888
          MITM: true
        run: npm run mitm --workspaces --if-present
