name: Mitm

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.8.4']
        spec:
          - '0.16.1'
        node:
          - 20.18 # without require(esm)
          - 20.19 # with require(esm), see https://nodejs.org/en/blog/release/v20.19.0/#requireesm-is-now-enabled-by-default
          - 22

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main
        with:
          node_version: ${{ matrix.node }}

      - run: pnpm build

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip3 install mitmproxy~=10.0.0

      - uses: dfinity/setup-dfx@main

      - name: running dfx
        working-directory: e2e/node
        id: dfx
        run: |
          dfx start --background

      - name: deploy canisters
        working-directory: e2e/node
        run: |
          dfx deploy counter

      - name: Running mitmdump
        id: mitmdump
        run: |
          set -ex
          mitmdump -p 8888 --mode reverse:http://localhost:4943 \
            --modify-headers '/~s/Transfer-Encoding/' \
            --modify-body '/~s/Hello/Hullo' \
            &
          sleep 20

      - name: mitm e2e
        run: pnpm run -F @e2e/node mitm

  aggregate:
    name: mitm:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
