name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      semverBump:
        description: 'Specify next SemVer version (either of: "patch", "minor", "major", "prepatch", "preminor", "premajor", or custom SemVer compatible version (e.g. "0.32.1-beta.1", or "1.0.0"))'
        type: string
        required: true
        default: 'patch'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main
        with:
          node_version_file: '.nvmrc'
          
      - name: Set up git config
        run: |
          git config author.email "${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com"
          git config author.name "${{ github.event.sender.login }}"
          git config committer.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config committer.name "GitHub Actions Bot"
          git config user.email "${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com"
          git config user.name "${{ github.event.sender.login }}"
      - name: Create release Pull request & GitHub Release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: pnpm release ${{ inputs.semverBump }}
