name: Check Formatting
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ghc: ['8.8.4']
        spec:
          - release-0.16 # https://github.com/dfinity-lab/ic-ref/tree/release-0.16
        node:
          - 22
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main
        with:
          node_version: ${{ matrix.node }}

      - run: pnpm prettier:check

  aggregate:
    name: format:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
