# TODO: remove this workflow once the action works
name: Tmp publish docs

on:
  pull_request:

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'luca/SDK-2264-push-docs' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main
        with:
          node_version_file: '.nvmrc'

      - uses: dfinity/ci-tools/actions/extract-version@luca/extract-version-action
        id: extract-version
        with:
          file: 'package.json'

      - name: Prepare version
        id: ver
        run: |
          echo "version=v${{ steps.extract-version.outputs.major }}" >> $GITHUB_OUTPUT

      - name: Build docs for version ${{ steps.ver.outputs.version }}
        working-directory: docs
        env:
          BASE_PATH: /core/${{ steps.ver.outputs.version }}/
        run: pnpm build --outDir dist/${{ steps.ver.outputs.version }}

      - name: Build docs for version latest
        working-directory: docs
        env:
          BASE_PATH: /core/latest/
        run: pnpm build --outDir dist/latest

      - name: Checkout icp-pages branch
        uses: actions/checkout@v4
        with:
          ref: icp-pages
          path: icp-pages

      - name: Assemble docs
        uses: dfinity/ci-tools/actions/assemble-docs@62c77c0025a556278392c17d5a9d7f013113e5a6
        with:
          docs_output_dir: 'docs/dist'
          docs_version: ${{ steps.ver.outputs.version }}
          docs_version_label: ${{ steps.ver.outputs.version }}
          latest_version: ${{ steps.ver.outputs.version }}
          icp_pages_dir: 'icp-pages'
          github_token: ${{ secrets.GITHUB_TOKEN }}
