name: Unit tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc: ['8.8.4']
        spec:
          - '0.16.1'
        node:
          - 20.18 # without require(esm)
          - 20.19 # with require(esm), see https://nodejs.org/en/blog/release/v20.19.0/#requireesm-is-now-enabled-by-default
          - 22

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
        with:
          node-version: ${{ matrix.node }}

      # build monorepo incl. each subpackage
      - run: npm run build

      # test monorepo incl. each subpackage
      - run: npm run test
        env:
          CI: true

  aggregate:
    name: unit:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
